[pytest]
testpaths = tests
pythonpath = .
addopts = -q
filterwarnings =
    ignore::DeprecationWarning
    ignore:The httpx module is deprecated
    ignore:Using `httpx` with `starlette.testclient` is deprecated
